#
# This file is part of pyperplan.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

"""
Classes and functions that traverse the PDDL abstract syntax tree (AST)
generated by parser.py, thereby creating the PDDL data structure.
"""

from typing import Any

from . import pddl


class SemanticError(Exception):
    """Exception indicating an error during traversal of AST."""

    def __init__(self, value: str) -> None:
        # ``value`` is the error message.
        self.value = value

    def __str__(self) -> str:
        return repr(self.value)


class Visitable:
    """Base class of the Visitor Pattern that every AST node derives from.

    The ``accept`` method calls the appropriate method of the visitor.
    """

    def __init__(self, vname: str | None = None) -> None:
        # ``vname`` is the name of the visitor callback to call for this node.
        self._visitor_name = vname

    def accept(self, visitor: Any) -> None:
        if self._visitor_name is None:
            raise ValueError("Error: visit method of uninitialized visitor called!")
        # Get the appropriate method of the visitor instance and call it.
        m = getattr(visitor, self._visitor_name)
        if not callable(m):
            raise ValueError(
                f"Error: cannot call undefined method: {self._visitor_name} on visitor"
            )
        m(self)


class PDDLVisitor:
    """
    The standard tree traversal PDDL Visitor from which other Visitors derive.

    In each node, the Visitor just applies itself to all its children.
    """

    def visit_domain_def(self, node: Any) -> None:
        node.requirements.accept(self)
        if node.types is not None:
            for t in node.types:
                t.accept(self)
        if node.constants is not None:
            for c in node.constants:
                c.accept(self)
        node.predicates.accept(self)
        if node.actions is not None:
            for a in node.actions:
                a.accept(self)

    def visit_problem_def(self, node: Any) -> None:
        for o in node.objects:
            o.accept(self)
        node.init.accept(self)
        node.goal.accept(self)

    def visit_predicates_stmt(self, node: Any) -> None:
        for p in node.predicates:
            p.accept(self)

    def visit_action_stmt(self, node: Any) -> None:
        for p in node.parameters:
            p.accept(self)
        node.precond.accept(self)
        node.effect.accept(self)

    def visit_formula(self, node: Any) -> None:
        for c in node.children:
            c.accept(self)

    def visit_type(self, node: Any) -> None:
        return  # nothing to do right now

    def visit_effect_stmt(self, node: Any) -> None:
        node.formula.accept(self)

    def visit_precondition_stmt(self, node: Any) -> None:
        node.formula.accept(self)

    def visit_requirements_stmt(self, node: Any) -> None:
        for k in node.keywords:
            k.accept(self)

    def visit_predicate(self, node: Any) -> None:
        for p in node.parameters:
            p.accept(self)

    def visit_variable(self, node: Any) -> None:
        pass

    def visit_init_stmt(self, node: Any) -> None:
        for p in node.predicates:
            p.accept(self)

    def visit_goal_stmt(self, node: Any) -> None:
        node.formula.accept(self)

    def visit_predicate_instance(self, node: Any) -> None:
        return  # nothing to do right now

    def visit_object(self, node: Any) -> None:
        return  # nothing to do right now

    def visit_keyword(self, node: Any) -> None:
        return  # nothing to do right now


class TraversePDDLDomain(PDDLVisitor):
    """The PDDL-domain Visitor.

    Expands the functionality of the PDDLVisitor to traversal of ASTs that
    represent a PDDL-domain file. It results in the PDDL data structure
    (pddl.py) representation of the domain file.
    """

    def get_in(self, node: Any) -> Any:
        """Return the information stored for ``node`` during traversal."""
        return self._node_hash[node]

    def set_in(self, node: Any, val: Any) -> None:
        """Store ``val`` as the information for ``node`` during traversal."""
        self._node_hash[node] = val

    def __init__(self) -> None:
        self._types: dict[str, pddl.Type] = {}
        self._predicates: dict[str, pddl.Predicate] = {}
        self._node_hash: dict[Any, Any] = {}
        self._requirements: set[str] = set()
        self._actions: dict[str, pddl.Action] = {}
        self.domain: pddl.Domain | None = None
        self._object_type = pddl.Type("object", None)
        self._constants: dict[str, pddl.Type] = {}

    def visit_domain_def(self, node: Any) -> None:
        """Visits a PDDL domain definition."""
        explicit_object_def = False

        # Requirements statement is optional.
        if node.requirements:
            node.requirements.accept(self)

        # Visit all type definitions.
        if node.types is not None:
            for t in node.types:
                if t.name == "object":
                    explicit_object_def = True
                t.accept(self)
                type_def = self.get_in(t)
                self._types[type_def.name] = type_def
        # Add the default object type to the type definitions,
        # if it was not explicitly created.
        if not explicit_object_def:
            self._types["object"] = self._object_type

        # Link all types to their parent types directly.
        for t in self._types.values():
            # Object type has no parent.
            if t.name == "object":
                continue
            if t.parent not in self._types:
                raise SemanticError(f"Error unknown parent type: {t.parent}")
            t.parent = self._types[t.parent]

        # Visit all predicates.
        node.predicates.accept(self)

        # Visit all actions.
        if node.actions is not None:
            for a in node.actions:
                a.accept(self)
                action = self.get_in(a)
                if action.name in self._actions:
                    raise SemanticError(
                        f"Error: action with name {action.name} "
                        "has already been defined"
                    )
                self._actions[action.name] = action

        # Visit all constants.
        if node.constants is not None:
            for c in node.constants:
                c.accept(self)

        # Finally generate PDDL domain data structure.
        self.domain = pddl.Domain(
            node.name, self._types, self._predicates, self._actions, self._constants
        )

    def visit_object(self, node: Any) -> None:
        """Visits a PDDL object definition."""
        type_name = node.type_name
        if type_name is None:
            type_name = "object"
        if type_name not in self._types:
            raise SemanticError(
                f"Error: unknown type {type_name} used in object definition!"
            )
        if node.name in self._constants:
            raise SemanticError(
                f"Error: multiple defines of object with name {node.name}"
            )
        # Add constant with its corresponding type to the constants dict.
        self._constants[node.name] = self._types[type_name]

    def visit_type(self, node: Any) -> None:
        """Visits a PDDL type definition."""
        # Store matching parent type in node
        # (if none is given, it's always object)
        if node.parent is None:
            self.set_in(node, pddl.Type(node.name, "object"))
        else:
            self.set_in(node, pddl.Type(node.name, node.parent))

    def visit_requirements_stmt(self, node: Any) -> None:
        """Visits a PDDL requirement statement."""
        # Visit all requirement keywords...
        for k in node.keywords:
            k.accept(self)
            requirement_name = self.get_in(k)
            # ... and add them to the requirement list.
            self._requirements.add(requirement_name)

    def visit_keyword(self, node: Any) -> None:
        """Visits a PDDL keyword."""
        # Nothing to do but to store its name in the node.
        self.set_in(node, node.name)

    def visit_predicates_stmt(self, node: Any) -> None:
        """Visits a PDDL predicate statement."""
        # Visit all predicates in the predicate statement.
        for p in node.predicates:
            p.accept(self)
            predicate = self.get_in(p)
            # Check for duplicate predicate definitions.
            if predicate.name in self._predicates:
                raise SemanticError(
                    f"Error predicate with name {predicate.name} "
                    "has already been defined"
                )
            # Add to predicate list.
            self._predicates[predicate.name] = predicate

    def visit_predicate(self, node: Any) -> None:
        """Visits a PDDL predicate."""
        signature: pddl.Signature = []
        # Visit all predicate parameters and append them to the signature.
        for v in node.parameters:
            v.accept(self)
            signature.append(self.get_in(v))
        # Create new PDDL predicate and store it in node.
        self.set_in(node, pddl.Predicate(node.name, signature))

    def visit_variable(self, node: Any) -> None:
        """Visits a PDDL variable."""
        # If there is no type given, it is always of type 'object'.
        if not node.typed:
            self.set_in(node, (node.name, [self._types["object"]]))
        else:
            # Visit all type declarations of the variable.
            typelist: list[pddl.Type] = []
            for t in node.types:
                # Check whether they have been defined.
                if t not in self._types:
                    raise SemanticError(
                        f"Error unknown type {t} used in predicate definition"
                    )
                typelist.append(self._types[t])
            # Store variable information (var_name, tuple(types)) in node.
            self.set_in(node, (node.name, tuple(typelist)))

    def visit_action_stmt(self, node: Any) -> None:
        """Visits a PDDL action statement."""
        signature: pddl.Signature = []
        # Visit all parameters and create the signature.
        for v in node.parameters:
            v.accept(self)
            signature.append(self.get_in(v))

        # Visit the precondition statement.
        node.precond.accept(self)
        precond = self.get_in(node.precond)

        # Visit the effect statement.
        node.effect.accept(self)
        effect = self.get_in(node.effect)

        # Create new PDDL action and store in node.
        self.set_in(node, pddl.Action(node.name, signature, precond, effect))

    def add_precond(self, precond: list[pddl.Predicate], c: Any) -> None:
        """Add the precondition described by formula ``c`` to the ``precond`` list."""
        from .parser import Variable

        predicate_def = self._predicates[c.key]
        signature: pddl.Signature = []
        # Check for correct number of arguments.
        if len(c.children) != len(predicate_def.signature):
            raise SemanticError(
                f"Error: wrong number of arguments for predicate {c.key} "
                "in precondition of action"
            )
        # Apply to all arguments.
        for count, v in enumerate(c.children):
            name = v.key.name if isinstance(v.key, Variable) else v.key
            signature.append((name, predicate_def.signature[count][1]))

        # Add predicate to precondition list.
        precond.append(pddl.Predicate(c.key, signature))

    def visit_precondition_stmt(self, node: Any) -> None:
        """Visits a PDDL precondition statement."""
        precond: list[pddl.Predicate] = []
        formula = node.formula
        # For now we only allow and in the precondition.
        if formula.key == "and":
            # Apply to all predicates in precondition.
            for c in formula.children:
                if not isinstance(c.key, str):
                    keys = "".join(c2.key.name + " " for c2 in formula.children)
                    raise SemanticError(f"Error predicate with non str key: {keys}")
                # Check whether predicate was defined.
                if c.key not in self._predicates:
                    raise SemanticError(
                        f"Error unknown predicate {c.key} "
                        "used in precondition of action"
                    )
                self.add_precond(precond, c)
        else:
            # If not 'and' we only allow a single predicate in precondition.
            if formula.key not in self._predicates:
                raise SemanticError("Error: predicate in precondition is not in CNF")
            # Call helper.
            self.add_precond(precond, formula)
        self.set_in(node, precond)

    def add_effect(self, effect: pddl.Effect, c: Any) -> None:
        """Add the effect described by formula ``c`` to ``effect``.

        The effect is added to ``effect.addlist`` or ``effect.dellist``
        depending on whether ``c`` is negated.
        """
        from .parser import Variable  # Imported here to avoid a cyclic import.

        next_predicate = None
        is_negative = False
        if c.key == "not":
            # This is a negative effect, only one child allowed.
            if len(c.children) != 1:
                raise SemanticError(
                    "Error not statement with multiple children in effect of action"
                )
            next_predicate = c.children[0]
            is_negative = True
        else:
            next_predicate = c
        # Check whether predicate was defined previously.
        if next_predicate.key not in self._predicates:
            raise SemanticError(
                f"Error: unknown predicate {next_predicate.key} "
                "used in effect of action"
            )
        if next_predicate is None:
            raise SemanticError("Error: NoneType predicate used in effect of action")
        predicate_def = self._predicates[next_predicate.key]
        signature: pddl.Signature = []
        # Check whether predicate is used with the correct signature.
        if len(next_predicate.children) != len(predicate_def.signature):
            raise SemanticError(
                f"Error: wrong number of arguments for predicate "
                f"{next_predicate.key} in effect of action"
            )
        # Apply to all parameters.
        for count, v in enumerate(next_predicate.children):
            name = v.key.name if isinstance(v.key, Variable) else v.key
            signature.append((name, predicate_def.signature[count][1]))

        # Add a new effect to the positive or negative effects respectively.
        if is_negative:
            effect.dellist.add(pddl.Predicate(next_predicate.key, signature))
        else:
            effect.addlist.add(pddl.Predicate(next_predicate.key, signature))

    def visit_effect_stmt(self, node: Any) -> None:
        """Visits a PDDL effect statement."""
        formula = node.formula
        effect = pddl.Effect()
        # For now we only allow 'and' in the effect.
        if formula.key == "and":
            for c in formula.children:
                self.add_effect(effect, c)
        else:
            self.add_effect(effect, formula)
        self.set_in(node, effect)


class TraversePDDLProblem(PDDLVisitor):
    """The PDDL-problem Visitor.

    Expands the functionality of the PDDLVisitor to traversal of ASTs that
    represent a PDDL-problem file. It results in the PDDL data structure
    (pddl.py) representation of the problem file.
    """

    def get_in(self, node: Any) -> Any:
        """Return the information stored for ``node`` during traversal."""
        return self._node_hash[node]

    def set_in(self, node: Any, val: Any) -> None:
        """Store ``val`` as the information for ``node`` during traversal."""
        self._node_hash[node] = val

    def get_problem(self) -> "pddl.Problem | None":
        """Getter for the resulting pddl-problem data structure."""
        return self._problem_def

    def __init__(self, domain: pddl.Domain) -> None:
        # ``domain`` is the corresponding pddl.Domain data structure.
        self._domain = domain
        self._node_hash: dict[Any, Any] = {}
        self._objects: dict[str, pddl.Type] = {}
        self._problem_def: pddl.Problem | None = None

    def visit_problem_def(self, node: Any) -> None:
        """Visits a PDDL-problem definition."""
        # Check whether the domain name referenced in the problem file matches
        # the supplied domain data structure.
        if node.domain_name != self._domain.name:
            raise SemanticError(
                f"Error trying to parse problem file with domain: "
                f"{node.domain_name} together with a domain file that "
                f"specifies domain: {self._domain.name}"
            )
        # Apply to all object definitions.
        for o in node.objects:
            o.accept(self)

        # Apply to the initial state definition.
        node.init.accept(self)
        init_list = self.get_in(node.init)

        # Apply to the goal state definition.
        node.goal.accept(self)
        goal_list = self.get_in(node.goal)

        # Create the problem data structure.
        self._problem_def = pddl.Problem(
            node.name, self._domain, self._objects, init_list, goal_list
        )

    def visit_object(self, node: Any) -> None:
        """Visits a PDDL-problem object definition."""
        # Check for multiple definitions of objects.
        if node.name in self._objects:
            raise SemanticError(
                f"Error multiple defines of object with name {node.name}"
            )
        # Untyped objects get the standard type 'object'.
        if node.type_name is None:
            type_def = self._domain.types["object"]
        else:
            # Check whether the used type was introduced in the domain file.
            if node.type_name not in self._domain.types:
                raise SemanticError(
                    f"Error: unknown type {node.type_name} used in object definition!"
                )
            type_def = self._domain.types[node.type_name]
        self._objects[node.name] = type_def

    def visit_init_stmt(self, node: Any) -> None:
        """Visits a PDDL-problem initial state statement."""
        init_list: list[pddl.Predicate] = []
        # Apply to all predicates in the statement.
        for p in node.predicates:
            p.accept(self)
            init_list.append(self.get_in(p))
        self.set_in(node, init_list)

    def add_goal(self, goal: list[pddl.Predicate], c: Any) -> None:
        """Add the goal described by formula ``c`` to the ``goal`` list."""
        # Check whether predicate was introduced in domain file.
        if c.key not in self._domain.predicates:
            raise SemanticError(f"Error: unknown predicate {c.key} in goal definition")
        # Get predicate from the domain data structure.
        predicate_def = self._domain.predicates[c.key]
        signature: pddl.Signature = []
        # Check whether the predicate uses the correct signature.
        if len(c.children) != len(predicate_def.signature):
            raise SemanticError(
                f"Error: wrong number of arguments for predicate {c.key} in goal"
            )
        for count, v in enumerate(c.children):
            signature.append((v.key, predicate_def.signature[count][1]))
        # Add the predicate to the goal.
        goal.append(pddl.Predicate(c.key, signature))

    def visit_goal_stmt(self, node: Any) -> None:
        """Visits a PDDL-problem goal state statement."""
        formula = node.formula
        goal: list[pddl.Predicate] = []
        # For now we only allow 'and' in the goal.
        if formula.key == "and":
            for c in formula.children:
                if not isinstance(c.key, str):
                    keys = "".join(c2.key.name + " " for c2 in formula.children)
                    raise SemanticError(f"Error predicate with non str key: {keys}")
                self.add_goal(goal, c)
        else:
            # Otherwise only a single predicate is allowed (see above).
            if formula.key not in self._domain.predicates:
                raise SemanticError("Error: predicate in goal definition is not in CNF")
            self.add_goal(goal, formula)
        self.set_in(node, goal)

    def visit_predicate_instance(self, node: Any) -> None:
        """Visits a PDDL-problem predicate instance."""
        signature: pddl.Signature = []
        # Visit all parameters.
        for o in node.parameters:
            # Check whether the object was introduced as an object or as a
            # domain constant.
            if o in self._objects:
                o_type = self._objects[o]
            elif o in self._domain.constants:
                o_type = self._domain.constants[o]
            else:
                raise SemanticError(
                    f"Error: object {o} referenced in problem definition "
                    "- but not defined"
                )
            signature.append((o, o_type))
        self.set_in(node, pddl.Predicate(node.name, signature))
